blank_issues_enabled: false
contact_links:
  - name: Tasks
    url: https://github.com/openhwgroup/core-v-mcu/issues/new?template=task.md
    about: Tasks related to core-v-mcu.
  - name: Bugs
    url: https://github.com/openhwgroup/core-v-mcu/issues/new?template=bug.md
    about: Bugs related to core-v-mcu
